# Generated by Django 4.2.7 on 2026-02-16 02:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="profiles/default.png",
                max_length=255,
                null=True,
                verbose_name="profiles/",
            ),
        ),
    ]
